name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Run CI Tests
        run: |
          bash test.sh
